### ISSUE TITLE
Fix exception typos in LIC7

### ISSUE THREAD

**Issue by emilsjol** [Lussebullen/DD2480_DECIDE#62]
In LicAnalyzer.java, in lic7(InputHandler input) function:
First exception has typo, where it should say "...must be between 3 (inclusive) and..." instead of "...2 (inclusive) and...".
Second exception uses "input.NUMPOINTS - 2". I recommend just using "NUMPOINTS - 2" as it is less messy and equally as informative to us and eventual users.

**Comment by asirago** [comment]
Like you say, it should be 3. I have changed it. Please take a look at #63
